jobs:
  - build
  - test-api
  - test-sdk
  - test-sql:
      matrix:
        parameters:
          postgres-version: ["latest", "11-alpine", "12-alpine", "13-alpine", "14-alpine"]
  - make-gen-deltas
